Repository LinKuangren/PHP-WAW, pull requests merged in 2023-01, with the labels that each got.

#26 feat(#12): ajoute le style de la page de connexion
  public/img/imgHeader/imgFond.jpeg
  public/img/imgHeader/imgFondAuthentification.jpeg
  template/User/login.php
  template/layout.php
Labels: enhancement, front

#28 feat(#27): ajoute le style de la page d'inscription
  template/User/register.php
Labels: enhancement, front

#30 fix(#29): corrige le style de la page de création d'un road trip
  template/RoadTrip/add.php
Labels: bug, front

#33 Feature/32
  template/RoadTrip/add.php
  template/RoadTrip/edit.php
Labels: bug, back

#35 fix(#34): corrige le style de la page de détails d'un road trip
  tailwind.config.js
  template/RoadTrip/details.php
Labels: bug, front

#38 fix(#36): corrige le style de la page de modificaton d'un road trip
  template/RoadTrip/edit.php
Labels: bug, front

#39 fix(#37): corrige les erreurs de style restant de la page de création…
  template/RoadTrip/add.php
Labels: bug, front

#41 Feature/3
  public/img/menu/logo.png
  template/_navbar.php
  template/layout.php
Labels: enhancement, front

#43 Feature/20
  template/RoadTrip/index.php
Labels: enhancement, front
